# Generated by Django 5.2.7 on 2025-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='aitools'),
        ),
    ]
