# Generated by Django 5.2.7 on 2025-11-15 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0003_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='aitool',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
