# Generated by Django 5.2.7 on 2025-12-09 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0008_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('image', models.URLField(max_length=500)),
                ('features', models.TextField(blank=True, null=True)),
                ('how_it_works', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin', null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tools', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Submission',
                'verbose_name_plural': 'Tool Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
