# Generated by Django 5.2.7 on 2025-12-09 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0009_toolsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of tool features'),
        ),
        migrations.AddField(
            model_name='aitool',
            name='how_it_works',
            field=models.TextField(blank=True, help_text='Description of how the tool works', null=True),
        ),
        migrations.CreateModel(
            name='ToolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='aitools.aitool')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
