# Generated by Django 5.2.7 on 2025-12-09 21:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0010_aitool_features_aitool_how_it_works_toolmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review', models.TextField(blank=True, help_text='Optional review text', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='bloglike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bloglike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='bloglike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.RemoveField(
            model_name='toolsubmission',
            name='reviewed_by',
        ),
        migrations.AlterUniqueTogether(
            name='userfavorite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='user',
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_popular',
        ),
        migrations.AlterField(
            model_name='aitool',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of features as JSON array'),
        ),
        migrations.AlterField(
            model_name='aitool',
            name='link',
            field=models.URLField(blank=True, help_text='External URL to the AI tool', null=True),
        ),
        migrations.AlterField(
            model_name='toolmodel',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the model', null=True),
        ),
        migrations.AlterField(
            model_name='toolmodel',
            name='name',
            field=models.CharField(help_text='Model name (e.g., GPT-4, Claude 3)', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='toolmodel',
            unique_together={('tool', 'name')},
        ),
        migrations.AddField(
            model_name='toolrating',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='aitools.aitool'),
        ),
        migrations.AddField(
            model_name='toolrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='BlogComment',
        ),
        migrations.DeleteModel(
            name='BlogLike',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='ToolSubmission',
        ),
        migrations.DeleteModel(
            name='UserFavorite',
        ),
        migrations.AlterUniqueTogether(
            name='toolrating',
            unique_together={('user', 'tool')},
        ),
    ]
