# Generated by Django 5.2.7 on 2025-12-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0012_userfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='affiliate',
            field=models.BooleanField(default=False, help_text='Whether this tool is an affiliate link'),
        ),
    ]
