# Generated by Django 5.2.7 on 2025-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitools', '0016_newslettersubscriber_toolsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='anonymous_likes',
            field=models.PositiveIntegerField(default=0, help_text='Number of likes from anonymous users'),
        ),
    ]
